-- Create notes table
CREATE TABLE IF NOT EXISTS public.notes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    random_name TEXT NOT NULL,
    message VARCHAR(280) NOT NULL,
    mood TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    country TEXT NOT NULL,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anyone to read active (non-hidden) notes
CREATE POLICY "Allow public select" ON public.notes
    FOR SELECT
    USING (is_hidden = FALSE);

-- Policy: Allow public (anonymous and authenticated) to insert active notes
CREATE POLICY "Allow public insert" ON public.notes
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (is_hidden = FALSE);

-- Index on coordinates and visibility for fast leaflet bounding box queries
CREATE INDEX IF NOT EXISTS notes_lat_lng_idx ON public.notes(latitude, longitude) WHERE is_hidden = FALSE;
CREATE INDEX IF NOT EXISTS notes_created_at_idx ON public.notes(created_at DESC);

-- Enable Realtime replication for notes table (required for frontend subscription)
ALTER PUBLICATION supabase_realtime ADD TABLE public.notes;

-- Enable the pg_cron extension (allows scheduling queries inside the database)
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Schedule a daily job to delete notes older than 30 days (runs at midnight 00:00 every day)
SELECT cron.schedule(
    'delete-old-notes-job',
    '0 0 * * *',
    $$ DELETE FROM public.notes WHERE created_at < NOW() - INTERVAL '30 days' $$
);

-- Create active chat rooms table
CREATE TABLE IF NOT EXISTS public.chat_rooms (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create active chat room users table to track occupant count in real time
CREATE TABLE IF NOT EXISTS public.chat_room_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    room_id UUID NOT NULL REFERENCES public.chat_rooms(id) ON DELETE CASCADE,
    user_token TEXT NOT NULL UNIQUE, -- Unique user token generated by the client
    last_active_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.chat_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_room_users ENABLE ROW LEVEL SECURITY;

-- Policies: Allow public select for room info and users
CREATE POLICY "Allow public select chat_rooms" ON public.chat_rooms
    FOR SELECT USING (true);

CREATE POLICY "Allow public select chat_room_users" ON public.chat_room_users
    FOR SELECT USING (true);

-- Indices for performance
CREATE INDEX IF NOT EXISTS chat_room_users_room_id_idx ON public.chat_room_users(room_id);
CREATE INDEX IF NOT EXISTS chat_room_users_last_active_at_idx ON public.chat_room_users(last_active_at);

-- Function to join or create a chat room atomically (runs as security definer to bypass RLS)
CREATE OR REPLACE FUNCTION public.join_or_create_chat_room(
    p_user_token text,
    p_max_occupants integer
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_room_id uuid;
BEGIN
    -- Check if the user is already in a room
    SELECT room_id INTO v_room_id
    FROM public.chat_room_users
    WHERE user_token = p_user_token
    LIMIT 1;

    IF v_room_id IS NOT NULL THEN
        -- Keep their active timestamp fresh
        UPDATE public.chat_room_users
        SET last_active_at = now()
        WHERE user_token = p_user_token;
        
        RETURN v_room_id;
    END IF;

    -- Try to find a room with available space
    SELECT r.id INTO v_room_id
    FROM public.chat_rooms r
    LEFT JOIN public.chat_room_users u ON r.id = u.room_id
    GROUP BY r.id
    HAVING count(u.id) < p_max_occupants
    ORDER BY count(u.id) DESC -- Fill up near-full rooms first
    LIMIT 1;

    -- If no room is available, create a new one
    IF v_room_id IS NULL THEN
        INSERT INTO public.chat_rooms (id)
        VALUES (gen_random_uuid())
        RETURNING id INTO v_room_id;
    END IF;

    -- Add the user to the room
    INSERT INTO public.chat_room_users (room_id, user_token, last_active_at)
    VALUES (v_room_id, p_user_token, now())
    ON CONFLICT (user_token) DO UPDATE
    SET room_id = EXCLUDED.room_id, last_active_at = now();

    RETURN v_room_id;
END;
$$;

-- Secure the function: revoke execution from public roles and restrict it to service_role/postgres
REVOKE EXECUTE ON FUNCTION public.join_or_create_chat_room(text, integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.join_or_create_chat_room(text, integer) TO postgres, service_role;

-- Schedule a minutely job to clean up stale users and rooms
SELECT cron.schedule(
    'cleanup-stale-chat-users-and-rooms-job',
    '*/1 * * * *',
    $$ 
    DELETE FROM public.chat_room_users WHERE last_active_at < NOW() - INTERVAL '90 seconds';
    DELETE FROM public.chat_rooms WHERE id NOT IN (SELECT DISTINCT room_id FROM public.chat_room_users);
    $$
);


